# Generated by Django 3.0.2 on 2021-06-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('email', models.EmailField(default='unknown', max_length=254, unique=True, verbose_name='邮箱')),
                ('teach_id', models.CharField(default='unknown', max_length=10, unique=True, verbose_name='学号')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['create_time'],
            },
        ),
    ]
