# Generated by Django 3.0.2 on 2021-06-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='max_num',
            new_name='need_num',
        ),
        migrations.AddField(
            model_name='meeting',
            name='exa_num',
            field=models.IntegerField(default=0, verbose_name='实到人数'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='need_grade',
            field=models.CharField(default='123456789', max_length=10, verbose_name='应到年级'),
        ),
    ]
