# Generated by Django 3.0.2 on 2021-06-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20210613_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meet_theme',
            field=models.CharField(default='', max_length=50, verbose_name='活动主题'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meet_name',
            field=models.CharField(max_length=50, verbose_name='活动名称'),
        ),
    ]
