# Generated by Django 3.0.2 on 2021-06-14 07:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20210614_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signlist',
            name='meet_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='meet_uuid'),
        ),
        migrations.AlterField(
            model_name='signlist',
            name='stu_id',
            field=models.CharField(default='unknown', max_length=10, verbose_name='学号'),
        ),
    ]
