# Generated by Django 3.0.2 on 2021-06-12 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('grade', models.IntegerField(choices=[(1, '大一'), (2, '大二'), (3, '大三'), (4, '大四'), (5, '研一'), (6, '研二'), (7, '研三'), (8, '研四'), (9, '研五')], default=1, verbose_name='年级')),
                ('upload_people', models.CharField(default='', max_length=500)),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.DecimalField(decimal_places=0, max_digits=10)),
                ('file_path', models.CharField(max_length=500)),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
        ),
    ]
