# Generated by Django 3.0.2 on 2021-06-12 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='resource_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='resource_uuid'),
        ),
    ]
