# Generated by Django 3.0.2 on 2021-06-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20210612_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='total_num',
            field=models.IntegerField(default=0, verbose_name='年级总人数'),
        ),
    ]
